openapi: 3.0.2
info:
  title: HostServiceApi
  version: "1.0"
servers:
- url: /
paths:
  /authenticate:
    post:
      operationId: AuthenticatePairingCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticatePairingCodeRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticatePairingCodeResponseContent"
          description: AuthenticatePairingCode 200 response
  /internal/deprovision:
    post:
      operationId: DeprovisionDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeprovisionDeviceRequestContent"
      responses:
        "200":
          description: DeprovisionDevice 200 response
  /internal/host-config:
    get:
      operationId: GetHostConfig
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetHostConfigResponseContent"
          description: GetHostConfig 200 response
  /internal/log:
    post:
      operationId: RequestLog
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestLogRequestContent"
      responses:
        "200":
          description: RequestLog 200 response
  /internal/rotate-certs:
    post:
      operationId: RotateCertificates
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RotateCertificatesRequestContent"
        required: true
      responses:
        "200":
          description: RotateCertificates 200 response
  /internal/thumbnail:
    post:
      operationId: RequestThumbnail
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestThumbnailRequestContent"
        required: true
      responses:
        "200":
          description: RequestThumbnail 200 response
  /internal/version:
    get:
      operationId: GetVersion
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVersionResponseContent"
          description: GetVersion 200 response
  /pair:
    post:
      operationId: CreatePairingCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePairingCodeRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePairingCodeResponseContent"
          description: CreatePairingCode 200 response
components:
  schemas:
    AuthenticatePairingCodeRequestContent:
      example:
        accessCode: accessCode
        deviceId: deviceId
        pairingCode: pairingCode
      properties:
        deviceId:
          type: string
        pairingCode:
          format: password
          type: string
        accessCode:
          format: password
          type: string
      required:
      - accessCode
      - deviceId
      - pairingCode
      type: object
    AuthenticatePairingCodeResponseContent:
      example:
        regionName: regionName
        hostSettings:
          pairingTimeoutSeconds: 0.8008281904610115
          publishReportSchemaTopic: publishReportSchemaTopic
          publishDeprovisionTopic: publishDeprovisionTopic
          subUpdateTopic: subUpdateTopic
          subUpdateCertsTopic: subUpdateCertsTopic
          minimumIntervalPublishSeconds: 6.027456183070403
          subDeprovisionTopic: subDeprovisionTopic
          subUpdateThumbnailSubscriptionTopic: subUpdateThumbnailSubscriptionTopic
          publishReportActualConfigurationTopic: publishReportActualConfigurationTopic
          subUpdateLogSubscriptionTopic: subUpdateLogSubscriptionTopic
          mqttKeepaliveSeconds: 1.4658129805029452
          publishReportRegistrationTopic: publishReportRegistrationTopic
          mqttAlpnProtocol: mqttAlpnProtocol
          publishReportStatusTopic: publishReportStatusTopic
        mqttUri: mqttUri
        caCertificate: caCertificate
        deviceCertificate: deviceCertificate
        status: STANDBY
      properties:
        status:
          $ref: "#/components/schemas/PairingCodeAuthorizedStatus"
        caCertificate:
          type: string
        deviceCertificate:
          type: string
        mqttUri:
          type: string
        regionName:
          type: string
        hostSettings:
          $ref: "#/components/schemas/HostSettings"
      required:
      - status
      type: object
    CreatePairingCodeFailureData:
      properties:
        reason:
          $ref: "#/components/schemas/CreatePairingCodeFailureReason"
      required:
      - reason
      type: object
    CreatePairingCodeFailureReason:
      enum:
      - HOST_ID_MISMATCH
      - VERSION_NOT_SUPPORTED
      - DEVICE_TYPE_NOT_SUPPORTED
      type: string
    CreatePairingCodeRequestContent:
      example:
        deviceType: deviceType
        certificateSigningRequest: certificateSigningRequest
        hostId: hostId
        version: version
      properties:
        deviceType:
          type: string
        hostId:
          type: string
        certificateSigningRequest:
          type: string
        version:
          type: string
      required:
      - certificateSigningRequest
      - deviceType
      - hostId
      - version
      type: object
    CreatePairingCodeResponseContent:
      example:
        result:
          success:
            pairingTimeoutSeconds: 0.8008281904610115
            accessCode: accessCode
            deviceId: deviceId
            pairingCode: pairingCode
      properties:
        result:
          $ref: "#/components/schemas/CreatePairingCodeResult"
      required:
      - result
      type: object
    CreatePairingCodeResult:
      oneOf:
      - $ref: "#/components/schemas/success"
      - $ref: "#/components/schemas/failure"
    CreatePairingCodeSuccessData:
      example:
        pairingTimeoutSeconds: 0.8008281904610115
        accessCode: accessCode
        deviceId: deviceId
        pairingCode: pairingCode
      properties:
        deviceId:
          type: string
        pairingCode:
          format: password
          type: string
        accessCode:
          format: password
          type: string
        pairingTimeoutSeconds:
          type: number
      required:
      - accessCode
      - deviceId
      - pairingCode
      - pairingTimeoutSeconds
      type: object
    DeprovisionDeviceRequestContent:
      example:
        reason: DEPROVISIONED
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        reason:
          $ref: "#/components/schemas/DeprovisionReason"
        timestamp:
          format: date-time
          type: string
      type: object
    DeprovisionReason:
      enum:
      - DEPROVISIONED
      - EXPIRED
      - UNKNOWN
      type: string
    DeviceType:
      enum:
      - SOURCE
      - DESTINATION
      - BOTH
      type: string
    GetHostConfigResponseContent:
      example:
        thumbnailMaximumSizeKB: 0.8008281904610115
        authenticatePairingCodeUrl: authenticatePairingCodeUrl
        deviceTypes:
        - SOURCE
        - SOURCE
        createPairingCodeUrl: createPairingCodeUrl
        logFileMaximumSizeKB: 6.027456183070403
        serviceId: serviceId
        serviceName: serviceName
      properties:
        serviceId:
          type: string
        serviceName:
          type: string
        deviceTypes:
          items:
            $ref: "#/components/schemas/DeviceType"
          type: array
        thumbnailMaximumSizeKB:
          type: number
        logFileMaximumSizeKB:
          type: number
        createPairingCodeUrl:
          type: string
        authenticatePairingCodeUrl:
          type: string
      required:
      - authenticatePairingCodeUrl
      - createPairingCodeUrl
      - deviceTypes
      - logFileMaximumSizeKB
      - serviceId
      - serviceName
      - thumbnailMaximumSizeKB
      type: object
    GetVersionResponseContent:
      example:
        version:
          version: 1.0.2
      properties:
        version:
          $ref: "#/components/schemas/ProtocolVersion"
      required:
      - version
      type: object
    HostSettings:
      example:
        pairingTimeoutSeconds: 0.8008281904610115
        publishReportSchemaTopic: publishReportSchemaTopic
        publishDeprovisionTopic: publishDeprovisionTopic
        subUpdateTopic: subUpdateTopic
        subUpdateCertsTopic: subUpdateCertsTopic
        minimumIntervalPublishSeconds: 6.027456183070403
        subDeprovisionTopic: subDeprovisionTopic
        subUpdateThumbnailSubscriptionTopic: subUpdateThumbnailSubscriptionTopic
        publishReportActualConfigurationTopic: publishReportActualConfigurationTopic
        subUpdateLogSubscriptionTopic: subUpdateLogSubscriptionTopic
        mqttKeepaliveSeconds: 1.4658129805029452
        publishReportRegistrationTopic: publishReportRegistrationTopic
        mqttAlpnProtocol: mqttAlpnProtocol
        publishReportStatusTopic: publishReportStatusTopic
      properties:
        mqttAlpnProtocol:
          type: string
        pairingTimeoutSeconds:
          type: number
        minimumIntervalPublishSeconds:
          type: number
        mqttKeepaliveSeconds:
          type: number
        subUpdateTopic:
          type: string
        subUpdateThumbnailSubscriptionTopic:
          type: string
        publishReportSchemaTopic:
          type: string
        publishReportRegistrationTopic:
          type: string
        publishReportStatusTopic:
          type: string
        publishReportActualConfigurationTopic:
          type: string
        subUpdateCertsTopic:
          type: string
        publishDeprovisionTopic:
          type: string
        subDeprovisionTopic:
          type: string
        subUpdateLogSubscriptionTopic:
          type: string
      required:
      - minimumIntervalPublishSeconds
      - mqttAlpnProtocol
      - mqttKeepaliveSeconds
      - pairingTimeoutSeconds
      - publishDeprovisionTopic
      - publishReportActualConfigurationTopic
      - publishReportRegistrationTopic
      - publishReportSchemaTopic
      - publishReportStatusTopic
      - subDeprovisionTopic
      - subUpdateCertsTopic
      - subUpdateLogSubscriptionTopic
      - subUpdateThumbnailSubscriptionTopic
      - subUpdateTopic
      type: object
    PairingCodeAuthorizedStatus:
      enum:
      - STANDBY
      - CLAIMED
      type: string
    ProtocolVersion:
      example:
        version: 1.0.2
      properties:
        version:
          default: 1.0.2
          type: string
      type: object
    RequestLogRequestContent:
      example:
        remotePath: remotePath
        expiresAt: 2000-01-23T04:56:07.000+00:00
      properties:
        expiresAt:
          format: date-time
          type: string
        remotePath:
          type: string
      type: object
    RequestThumbnailRequestContent:
      example:
        requests:
          key:
            headers:
              key: headers
            remotePath: remotePath
            localPath: localPath
            periodSeconds: 0.8008281904610115
            expiresAt: 2000-01-23T04:56:07.000+00:00
            maxSizeKB: 6.027456183070403
      properties:
        requests:
          additionalProperties:
            $ref: "#/components/schemas/ThumbnailRequest"
          type: object
      required:
      - requests
      type: object
    RotateCertificatesRequestContent:
      example:
        regionName: regionName
        mqttUri: mqttUri
        deviceCertificate: deviceCertificate
      properties:
        mqttUri:
          type: string
        deviceCertificate:
          type: string
        regionName:
          type: string
      required:
      - deviceCertificate
      - mqttUri
      type: object
    StringMap:
      additionalProperties:
        type: string
      type: object
    ThumbnailRequest:
      example:
        headers:
          key: headers
        remotePath: remotePath
        localPath: localPath
        periodSeconds: 0.8008281904610115
        expiresAt: 2000-01-23T04:56:07.000+00:00
        maxSizeKB: 6.027456183070403
      properties:
        periodSeconds:
          type: number
        expiresAt:
          format: date-time
          type: string
        maxSizeKB:
          type: number
        localPath:
          type: string
        remotePath:
          type: string
        headers:
          additionalProperties:
            type: string
          type: object
      type: object
    ThumbnailRequestMap:
      additionalProperties:
        $ref: "#/components/schemas/ThumbnailRequest"
      type: object
    success:
      example:
        success:
          pairingTimeoutSeconds: 0.8008281904610115
          accessCode: accessCode
          deviceId: deviceId
          pairingCode: pairingCode
      properties:
        success:
          $ref: "#/components/schemas/CreatePairingCodeSuccessData"
      required:
      - success
      title: success
      type: object
    failure:
      properties:
        failure:
          $ref: "#/components/schemas/CreatePairingCodeFailureData"
      required:
      - failure
      title: failure
      type: object
